version: '3'

volumes:
  data:
services:
  grader:
    image: apluslms/run-mooc-grader:1.12
    #command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8080"]
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aplus:/tmp/aplus
      - .:/srv/courses/default:ro
      # mount the mooc-grader code
      #- $HOME/mooc-grader:/src/grader:ro
      #- $HOME/mooc-grader:/srv/grader
      #- .:/srv/grader/courses/default:ro
    ports:
      - "8080:8080"
      - "5679:5678"
  plus:
    image: apluslms/run-aplus-front:1.12
    #command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - data:/data
      # mount the A+ code
      #- $HOME/a-plus:/src/aplus:ro
      #- $HOME/a-plus:/srv/aplus
      # custom local database setup for testing
      #- ./tools/aplus-init.sh:/srv/aplus-init.sh:ro
      #- ./tools/test-bench-course-mod.py:/srv/test-bench-course-mod.py:ro
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - grader
  acos:
    image: apluslms/run-acos-server
    user: $USER_ID:$USER_GID
    ports:
      - "3000:3000"
    # depends_on is only used to control the start-up order of the containers so that
    # the ACOS container would more likely be assigned the IP address hardcoded into the course configuration
    depends_on:
      - plus
      - grader
    #volumes:
    #  - ./_data/acos/:/var/log/acos
