test_groups:
  - module: grader_tests
    display_name: Grader tests

validation:
  display_name: Input validation
  tasks:
    - type: python_import
      display_name: "The submitted file is a Python module that can be imported and defines the function times_two."
      file: submission.py
      attrs:
        times_two: function
    - type: python_syntax
      display_name: "The submitted file has correct Python syntax."
      file: submission.py
